---
- name: install required packages
  apt:
    name: "{{ glusterfs_packages }}"
    state: present

- name: Add PPA stable repository
  ansible.builtin.apt_repository:
    repo: ppa:gluster/glusterfs-7

- name: Install glusterfs packages
  apt:
    name:
      - glusterfs-server
      - glusterfs-client
    state: present

- name: Enable and start glusterd service
  service:
    name: glusterd
    state: started
    enabled: yes
